export interface Insert{
    category:string,
    title:string,
    youtube_url:any;
    details:string,
    status:number,
    status_text:number,
    title_ar:string,
    title_en:string,
    details_ar:string,
    details_en:string,
    images:any,
    image:any,
    cover:string,
    is_featured:number,
    adv_type:any,
    approved_at:string,
    not_approved_at:string,
    not_approved_reason:string,
    expired_at:string
}